unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

set-option -sg escape-time 10
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# vi keys for switching panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# One Dark Theme
run-shell "$HOME/.config/tmux/onedark-theme.tmux"
